SET SCHEMA FN24_45750;

CREATE OR REPLACE TRIGGER TRIG_BEFORE_INSERT_AUTHOR
BEFORE INSERT ON Authors
REFERENCING NEW AS N
FOR EACH ROW
WHEN (N.YEAROFLASTPUBLISHEDBOOK > YEAR(CURRENT_DATE))
    SIGNAL SQLSTATE '75999' ('YEAROFLASTPUBLISHEDBOOK is INVALID!!!!!');


INSERT INTO Authors(ALIAS, FIRSTNAME, SECONDNAME, BIRTHDATE, YEAROFFIRSTPUBLISHEDBOOK, YEAROFLASTPUBLISHEDBOOK)
VALUES ('Unknown', 'Unknown', 'Unknown', 2000, 2000, 2050);


CREATE OR REPLACE TRIGGER TRIG_BEFORE_INSERT_BOOKS
BEFORE INSERT ON Books
REFERENCING NEW AS B
FOR EACH ROW
WHEN (B.ID IN (SELECT Id FROM BOOKS))
    SIGNAL SQLSTATE '75999' ('Book already added!!!!!!');


INSERT INTO Books(Id, Name, YEAROFPUBLICATION) VALUES (default, 'Harry Potter', 1997);
