SET SCHEMA FN24_45750;

CREATE VIEW BookAuthor
AS
SELECT B.Name AS BOOKNAME, A.Alias AS AUTHORALIAS
FROM BOOKS B, AUTHORS A
WHERE B.AUTHORSHOUSEREGISTRATIONNUMBER = A.AUTHORSHOUSEREGISTRATIONNUMBER;



CREATE VIEW BOOKSGENRES
AS
SELECT B.Name AS BOOKNAME, G.GENRENAME AS GENRE
FROM BOOKS B JOIN HASGENRE G ON B.ID = G.BOOKID;


SELECT * FROM BookAuthor;

SELECT * FROM BOOKSGENRES;